---
version: '2'

linters:
  enable:
    - nonamedreturns

  exclusions:
    paths:
      - ^triplebyte$
      - wasm\/calc\/content\/

  settings:
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`. Such cases aren't reported by default.
      check-type-assertions: true

      # List of functions to exclude from checking, where each entry is a single function to exclude.
      # See https://github.com/kisielk/errcheck#excluding-functions for details.
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
        - fmt.Fprintf
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - io/ioutil.ReadFile

      # Display function signature instead of selector.
      verbose: true
