---
version: 3

vars:
  GO_MODULE_DIRS:
    sh: fd --absolute-path --type file '^go.mod$' --exec bash -c 'echo {//}'

tasks:
  default: task --list-all

  fix:
    cmd:
      for:
        var: GO_MODULE_DIRS
      vars:
        GO_MODULE_DIR: '{{.ITEM}}'
      task: fix-one

  fix-one:
    internal: true
    requires:
      vars:
        - GO_MODULE_DIR
    label: 'fix:{{trimPrefix (printf "%s/" .ROOT_DIR) .GO_MODULE_DIR}}'
    sources:
      - '{{.GO_MODULE_DIR}}/go.mod'
      - '{{.GO_MODULE_DIR}}/go.sum'
      - '{{.GO_MODULE_DIR}}/**/*.go'
    cmd: go -C "{{.GO_MODULE_DIR}}" fix ./...

  modernise:
    cmd:
      for:
        var: GO_MODULE_DIRS
      vars:
        GO_MODULE_DIR: '{{.ITEM}}'
      task: modernise-one

  modernise-one:
    internal: true
    requires:
      vars:
        - GO_MODULE_DIR
    label: 'modernise:{{trimPrefix (printf "%s/" .ROOT_DIR) .GO_MODULE_DIR}}'
    sources:
      - '{{.GO_MODULE_DIR}}/go.mod'
      - '{{.GO_MODULE_DIR}}/go.sum'
      - '{{.GO_MODULE_DIR}}/**/*.go'
    cmd: go -C "{{.GO_MODULE_DIR}}" run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...

  format:
    cmd:
      for:
        var: GO_MODULE_DIRS
      vars:
        GO_MODULE_DIR: '{{.ITEM}}'
      task: format-one

  format-one:
    internal: true
    requires:
      vars:
        - GO_MODULE_DIR
    label: 'format:{{trimPrefix (printf "%s/" .ROOT_DIR) .GO_MODULE_DIR}}'
    sources:
      - '{{.GO_MODULE_DIR}}/**/*.go'
    cmd: gofumpt -w -extra . "{{.GO_MODULE_DIR}}"

  lint:
    cmd:
      for:
        var: GO_MODULE_DIRS
      vars:
        GO_MODULE_DIR: '{{.ITEM}}'
      task: lint-one

  lint-one:
    internal: true
    requires:
      vars:
        - GO_MODULE_DIR
    label: 'lint:{{trimPrefix (printf "%s/" .ROOT_DIR) .GO_MODULE_DIR}}'
    sources:
      - '{{.ROOT_DIR}}/.golangci.yaml'
      - '{{.GO_MODULE_DIR}}/go.mod'
      - '{{.GO_MODULE_DIR}}/go.sum'
      - '{{.GO_MODULE_DIR}}/**/*.go'
    cmd: cd "{{.GO_MODULE_DIR}}" && golangci-lint run --fix ./...

  toil:
    cmds:
      - task: fix
      - task: modernise
      - task: format
      - task: lint
