linters:
  enable-all: true

  disable:
    # These linters have all been deprecated.
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

    # This linter is literally exhausting. 🙄
    - exhaustruct

    # Unnecessary.
    - depguard

linters-settings:
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      # Standard section: captures all standard packages.
      - standard
      # Default section: contains all imports that could not be matched to another section type.
      - default
      # Custom section: groups all imports with the specified Prefix.
      - prefix(go.jlucktay.dev/golang-workbench)
      - prefix(go.jlucktay.dev/golang-workbench/cineworld)
      # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - blank
      # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - dot

    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true

  nlreturn:
    block-size: 2
